name: Continuos Integration

on:
  push:
    branches: [ "main", "testedockerfile" ]
  pull_request:
    branches: [ "main" ]

permissions:
  security-events: write
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4